<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT3KJlhy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT3KJlhy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT3KJlhy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT3KJlhy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerT3KJlhy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'T3KJlhy',
    'container.build_id' => '24c277f7',
    'container.build_time' => 1557213425,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT3KJlhy');
