<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFjYz1v2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFjYz1v2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFjYz1v2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFjYz1v2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFjYz1v2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FjYz1v2',
    'container.build_id' => 'dde03605',
    'container.build_time' => 1557212070,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFjYz1v2');
